 //-----------------------------------------------------------------------
 // <copyright file=" crm_com_platform.cs" company="T4NL Enterprises">
 // * Copyright (C) 2020 T4NL Enterprises All Rights Reserved
 // * version : 4.0.30319.42000
 // * author  : auto generated by T4
 // * FileName: crm_com_platform.cs
 // * history : Created by T4 03/31/2020 11:15:17 
 // </copyright>
 //-----------------------------------------------------------------------
 using System;
  
 namespace T4NL.Model
 {
     /// <summary>
     /// crm_com_platform Entity Model
     /// </summary>    
     [Serializable]
      public class crm_com_platform
     {
         /// <summary>
		   /// 
           /// </summary>
          public int Id { get; set; }
     
         /// <summary>
         /// 
         /// </summary>
          public double ComPlatformValue { get; set; }
     
         /// <summary>
         /// 1:百分比 2：固定金额
         /// </summary>
          public int Type { get; set; }
     
         /// <summary>
         /// 
         /// </summary>
          public int IsSelected { get; set; }
     
         /// <summary>
         /// 
         /// </summary>
          public DateTime UTime { get; set; }
     
         /// <summary>
         /// 
         /// </summary>
          public DateTime CTime { get; set; }
      }
 }
 